export const UPLOAD_ITEM_REQUEST = 'UPLOAD_ITEM_REQUEST';
export const UPLOAD_ITEM_SUCCESS = 'UPLOAD_ITEM_SUCCESS';
export const UPLOAD_ITEM_FAIL = 'UPLOAD_ITEM_FAIL';
export const UPLOAD_ITEM_RESET = 'UPLOAD_ITEM_RESET';

export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAIL = 'GET_ITEM_FAIL';
export const GET_ITEM_RESET = 'GET_ITEM_RESET';

export const DOWNLOAD_ITEM_REQUEST = 'DOWNLOAD_ITEM_REQUEST';
export const DOWNLOAD_ITEM_SUCCESS = 'DOWNLOAD_ITEM_SUCCESS';
export const DOWNLOAD_ITEM_FAIL = 'DOWNLOAD_ITEM_FAIL';
export const DOWNLOAD_ITEM_RESET = 'DOWNLOAD_ITEM_RESET';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';
export const DELETE_ITEM_RESET = 'DELETE_ITEM_RESET';